#!/usr/bin/env php
<?php
/**
 * Part of CodeIgniter Cli
 *
 * @author     Agus Tri Haryono <https://github.com/agusth24>
 * @license    MIT License
 * @copyright  2019 Agus Tri Haryono
 * @link       https://github.com/agusth24/modangci
 */

$path = __DIR__;
chdir($path);

/** @const ROOTPATH CodeIgniter project root directory */
define('ROOTPATH', __DIR__ . '/');

require "{$path}/vendor/autoload.php";

// generate CodeIgniter instance
$ci = require "{$path}/ci_instance.php";

//print_r($argv);exit();

$command = new \Modangci\Modangci($argc, $argv, $ci);
